name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: 'srv-cv335ojtq21c73f5dhhg'
          apiKey: 'rnd_QVUxXg62twNcnhgOgRekpVDpzEEp'
          multipleDeployment: false #optional, default true